"use server";

import { db } from "@/lib/db";
import { repairJobs, repairTasks, repairPhotos, customers, units, users, repairJobEvents, communicationLogs, actionReminders, partRequests, parts, suppliers, repairWorkers, repairFindings, repairBlockers, timeEntries } from "@/lib/db/schema";
import { requireRole } from "@/lib/auth-utils";
import { requireAnyAuth } from "@/lib/garage-auth";
import { eq, and, or, isNull, gte, lte, desc, asc, count, sql, inArray } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { recordGarageUpdate } from "./garage-sync";

/**
 * See note in src/actions/time-entries.ts: revalidatePath can throw
 * during the implicit re-render that follows a server action, which
 * surfaces as an opaque 500 on the POST. Wrap so the mutation result
 * still reaches the client even if the next render briefly hiccups.
 */
function safeRevalidate(path: string, type?: "layout" | "page") {
  try {
    if (type) revalidatePath(path, type);
    else revalidatePath(path);
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error(`[garage actions] safeRevalidate(${path}) failed:`, err);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// HELPER: create office notification for garage activity
// ─────────────────────────────────────────────────────────────────────────────

async function notifyOffice(
  repairJobId: string,
  title: string,
  description?: string,
  triggerEvent?: string
) {
  await db.insert(actionReminders).values({
    repairJobId,
    reminderType: "custom",
    title,
    description: description ?? null,
    autoGenerated: true,
    triggerEvent: triggerEvent ?? "garage_feedback",
  });
  safeRevalidate("/");
}

// ─────────────────────────────────────────────────────────────────────────────
// AUTO START: move to in_progress when a technician opens the repair
// ─────────────────────────────────────────────────────────────────────────────

const autoStartStatuses = ["new", "todo", "scheduled"];

export async function garageAutoStart(repairJobId: string) {
  const ctx = await requireAnyAuth();

  const [job] = await db
    .select({ status: repairJobs.status })
    .from(repairJobs)
    .where(eq(repairJobs.id, repairJobId));

  if (!job || !autoStartStatuses.includes(job.status)) return { changed: false };

  await db
    .update(repairJobs)
    .set({ status: "in_progress", updatedAt: new Date() })
    .where(eq(repairJobs.id, repairJobId));

  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: ctx.userId,
    eventType: "status_changed",
    fieldChanged: "status",
    oldValue: job.status,
    newValue: "in_progress",
    comment: "Auto-started when opened in garage",
  });

  await recordGarageUpdate(repairJobId, "work_started", ctx.userId);

  return { changed: true };
}

// ─────────────────────────────────────────────────────────────────────────────
// UPDATE TITLE (from garage)
// ─────────────────────────────────────────────────────────────────────────────

export async function updateRepairTitle(repairJobId: string, title: string) {
  const ctx = await requireAnyAuth();
  const trimmed = title.trim();
  if (!trimmed) throw new Error("Title cannot be empty");

  await db
    .update(repairJobs)
    .set({ title: trimmed, updatedAt: new Date() })
    .where(eq(repairJobs.id, repairJobId));

  return { success: true };
}

// ─────────────────────────────────────────────────────────────────────────────
// MARK DONE / NOT DONE (from garage)
// ─────────────────────────────────────────────────────────────────────────────

export async function garageMarkDone(repairJobId: string) {
  const ctx = await requireAnyAuth();

  await db
    .update(repairJobs)
    .set({
      status: "ready_for_check",
      finalCheckStatus: "pending",
      updatedAt: new Date(),
    })
    .where(eq(repairJobs.id, repairJobId));

  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: ctx.userId,
    eventType: "status_changed",
    fieldChanged: "status",
    newValue: "ready_for_check",
    comment: "Marked as ready for check by garage",
  });

  // Notify office
  const [jobInfo] = await db
    .select({ publicCode: repairJobs.publicCode })
    .from(repairJobs)
    .where(eq(repairJobs.id, repairJobId));
  await notifyOffice(
    repairJobId,
    `🔍 Ready for check — ${jobInfo?.publicCode ?? ""}`,
    "Repair has been marked done by the garage and is waiting for inspection",
    "garage_done"
  );

  await recordGarageUpdate(repairJobId, "ready_for_check", ctx.userId);

  return { success: true };
}

export async function garageMarkNotDone(repairJobId: string, reason: string) {
  const ctx = await requireAnyAuth();
  const trimmed = reason.trim();
  if (!trimmed) throw new Error("Reason is required");

  // Set status to blocked
  await db
    .update(repairJobs)
    .set({ status: "blocked", updatedAt: new Date() })
    .where(eq(repairJobs.id, repairJobId));

  // Log as event (visible in office timeline)
  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: ctx.userId,
    eventType: "status_changed",
    fieldChanged: "status",
    newValue: "blocked",
    comment: `Garage: niet klaar — ${trimmed}`,
  });

  // Also add as communication log (visible in office)
  await db.insert(communicationLogs).values({
    repairJobId,
    userId: ctx.userId,
    contactMethod: "in_person",
    direction: "inbound",
    contactPerson: ctx.userName ?? "Garage",
    summary: `⚠️ Niet klaar: ${trimmed}`,
  });

  await db
    .update(repairJobs)
    .set({ lastContactAt: new Date() })
    .where(eq(repairJobs.id, repairJobId));

  // Notify office
  const [jobInfo] = await db
    .select({ publicCode: repairJobs.publicCode })
    .from(repairJobs)
    .where(eq(repairJobs.id, repairJobId));
  await notifyOffice(
    repairJobId,
    `🔧 Garage: niet klaar — ${jobInfo?.publicCode ?? ""}`,
    trimmed,
    "garage_not_done"
  );

  await recordGarageUpdate(repairJobId, "job_blocked", ctx.userId);

  return { success: true };
}

// ─────────────────────────────────────────────────────────────────────────────
// TODAY's REPAIRS
// ─────────────────────────────────────────────────────────────────────────────

export async function getGarageRepairsToday() {
  const ctx = await requireAnyAuth();

  const now = new Date();
  const startOfDay = new Date(now);
  startOfDay.setHours(0, 0, 0, 0);
  const endOfDay = new Date(now);
  endOfDay.setHours(23, 59, 59, 999);

  const jobs = await db
    .select({
      id: repairJobs.id,
      publicCode: repairJobs.publicCode,
      title: repairJobs.title,
      status: repairJobs.status,
      priority: repairJobs.priority,
      dueDate: repairJobs.dueDate,
      customerName: customers.name,
      unitRegistration: units.registration,
      unitBrand: units.brand,
      unitModel: units.model,
      unitStorageLocation: units.storageLocation,
      unitCurrentPosition: units.currentPosition,
      assignedUserName: users.name,
      finalCheckStatus: repairJobs.finalCheckStatus,
      jobType: repairJobs.jobType,
      garageAdminMessage: repairJobs.garageAdminMessage,
      garageAdminMessageAt: repairJobs.garageAdminMessageAt,
      garageAdminMessageReadAt: repairJobs.garageAdminMessageReadAt,
    })
    .from(repairJobs)
    .leftJoin(customers, eq(repairJobs.customerId, customers.id))
    .leftJoin(units, eq(repairJobs.unitId, units.id))
    .leftJoin(users, eq(repairJobs.assignedUserId, users.id))
    .where(
      and(
        isNull(repairJobs.deletedAt),
        isNull(repairJobs.archivedAt),
        or(
          // Today's repairs (any status)
          and(
            gte(repairJobs.dueDate, startOfDay),
            lte(repairJobs.dueDate, endOfDay)
          ),
          // Active/waiting repairs regardless of due date
          inArray(repairJobs.status, [
            "in_progress",
            "waiting_parts",
            "waiting_customer",
            "blocked",
            "ready_for_check",
          ])
        )
      )
    )
    .orderBy(asc(repairJobs.priority), asc(repairJobs.title));

  // Get task counts per job
  const jobIds = jobs.map((j) => j.id);
  if (jobIds.length === 0) return [];

  const taskCounts = await db
    .select({
      repairJobId: repairTasks.repairJobId,
      total: count(),
      done: sql<number>`count(*) filter (where ${repairTasks.status} = 'done')`,
      problem: sql<number>`count(*) filter (where ${repairTasks.status} = 'problem')`,
    })
    .from(repairTasks)
    .groupBy(repairTasks.repairJobId);

  const countsMap = new Map(
    taskCounts.map((c) => [
      c.repairJobId,
      { total: Number(c.total), done: Number(c.done), problem: Number(c.problem) },
    ])
  );

  // Pull the actionable "next" task per job so the Today screen can offer a
  // one-tap "mark this done" affordance directly on the card. We pick the first
  // in-progress task; otherwise the first pending one. Sort order falls back
  // to insertion order via createdAt to keep behaviour stable.
  const candidateTasks = await db
    .select({
      id: repairTasks.id,
      repairJobId: repairTasks.repairJobId,
      title: repairTasks.title,
      titleEs: repairTasks.titleEs,
      titleNl: repairTasks.titleNl,
      status: repairTasks.status,
      createdAt: repairTasks.createdAt,
    })
    .from(repairTasks)
    .where(
      and(
        inArray(repairTasks.repairJobId, jobIds),
        inArray(repairTasks.status, ["in_progress", "pending"]),
      ),
    )
    .orderBy(asc(repairTasks.createdAt));

  const nextTaskMap = new Map<
    string,
    {
      id: string;
      title: string;
      titleEs: string | null;
      titleNl: string | null;
      status: "pending" | "in_progress";
    }
  >();
  for (const t of candidateTasks) {
    const existing = nextTaskMap.get(t.repairJobId);
    if (!existing) {
      nextTaskMap.set(t.repairJobId, {
        id: t.id,
        title: t.title,
        titleEs: t.titleEs,
        titleNl: t.titleNl,
        status: t.status as "pending" | "in_progress",
      });
      continue;
    }
    // Prefer in-progress over pending if we encounter one later.
    if (existing.status !== "in_progress" && t.status === "in_progress") {
      nextTaskMap.set(t.repairJobId, {
        id: t.id,
        title: t.title,
        titleEs: t.titleEs,
        titleNl: t.titleNl,
        status: "in_progress",
      });
    }
  }

  // Get part request counts per job
  const partCounts = await db
    .select({
      repairJobId: partRequests.repairJobId,
      total: count(),
      received: sql<number>`count(*) filter (where ${partRequests.status} = 'received')`,
      pending: sql<number>`count(*) filter (where ${partRequests.status} in ('requested', 'ordered', 'shipped'))`,
    })
    .from(partRequests)
    .groupBy(partRequests.repairJobId);

  const partsMap = new Map(
    partCounts.map((c) => [
      c.repairJobId,
      { total: Number(c.total), received: Number(c.received), pending: Number(c.pending) },
    ])
  );

  // Pick the "next part to receive" per job for one-tap mark-received from
  // the Today card. Prefer a shipped part (closest to arrival), fall back to
  // ordered, then requested. Within a status, the earliest expected delivery
  // wins; if no ETA exists, the oldest request wins.
  const candidatePartRequests = await db
    .select({
      id: partRequests.id,
      repairJobId: partRequests.repairJobId,
      partName: partRequests.partName,
      status: partRequests.status,
      expectedDelivery: partRequests.expectedDelivery,
      createdAt: partRequests.createdAt,
    })
    .from(partRequests)
    .where(
      and(
        inArray(partRequests.repairJobId, jobIds),
        sql`${partRequests.status} in ('requested', 'ordered', 'shipped')`,
      ),
    );

  const STATUS_PRIORITY: Record<string, number> = { shipped: 0, ordered: 1, requested: 2 };
  type NextPartInternal = {
    id: string;
    name: string;
    status: "requested" | "ordered" | "shipped";
    expectedDelivery: Date | null;
    createdAt: number;
  };
  const nextPartMap = new Map<string, NextPartInternal>();
  for (const pr of candidatePartRequests) {
    if (!pr.repairJobId) continue;
    const candidate: NextPartInternal = {
      id: pr.id,
      name: pr.partName,
      status: pr.status as "requested" | "ordered" | "shipped",
      expectedDelivery: pr.expectedDelivery ? new Date(pr.expectedDelivery) : null,
      createdAt: pr.createdAt ? new Date(pr.createdAt).getTime() : Infinity,
    };
    const existing = nextPartMap.get(pr.repairJobId);
    if (!existing) {
      nextPartMap.set(pr.repairJobId, candidate);
      continue;
    }
    const a = STATUS_PRIORITY[candidate.status] ?? 9;
    const b = STATUS_PRIORITY[existing.status] ?? 9;
    if (a < b) {
      nextPartMap.set(pr.repairJobId, candidate);
      continue;
    }
    if (a === b) {
      const at = candidate.expectedDelivery?.getTime();
      const bt = existing.expectedDelivery?.getTime();
      if (at != null && bt != null) {
        if (at < bt) nextPartMap.set(pr.repairJobId, candidate);
      } else if (at != null && bt == null) {
        nextPartMap.set(pr.repairJobId, candidate);
      } else if (at == null && bt == null) {
        if (candidate.createdAt < existing.createdAt) nextPartMap.set(pr.repairJobId, candidate);
      }
    }
  }

  // Get workers per job
  const workers = await db
    .select({
      repairJobId: repairWorkers.repairJobId,
      userName: users.name,
    })
    .from(repairWorkers)
    .innerJoin(users, eq(repairWorkers.userId, users.id))
    .where(inArray(repairWorkers.repairJobId, jobIds));

  const workersMap = new Map<string, string[]>();
  for (const w of workers) {
    const list = workersMap.get(w.repairJobId) ?? [];
    list.push(w.userName);
    workersMap.set(w.repairJobId, list);
  }

  // Som van werkelijke (onafgeronde) minuten per klus. We tonen
  // tussentijds bewust de echte tijd — kwartaalafronding hoort pas bij
  // facturatie, niet tijdens het werk (dan lijkt het of een 9-minuten
  // sessie "15m" wordt en daarna weer terugspringt bij pauze, wat
  // werkers het gevoel geeft dat de timer "fout" telt).
  const timeTotals = await db
    .select({
      repairJobId: timeEntries.repairJobId,
      totalMinutes: sql<number>`coalesce(sum(${timeEntries.durationMinutes}), 0)`,
    })
    .from(timeEntries)
    .where(inArray(timeEntries.repairJobId, jobIds))
    .groupBy(timeEntries.repairJobId);

  const timeMap = new Map(timeTotals.map((t) => [t.repairJobId, Number(t.totalMinutes)]));

  return jobs.map((job) => {
    const np = nextPartMap.get(job.id);
    return {
      ...job,
      tasks: countsMap.get(job.id) ?? { total: 0, done: 0, problem: 0 },
      parts: partsMap.get(job.id) ?? { total: 0, received: 0, pending: 0 },
      workers: workersMap.get(job.id) ?? [],
      totalMinutes: timeMap.get(job.id) ?? 0,
      nextTask: nextTaskMap.get(job.id) ?? null,
      nextPart: np
        ? {
            id: np.id,
            name: np.name,
            status: np.status,
            expectedDelivery: np.expectedDelivery,
          }
        : null,
    };
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// REPAIR DETAIL (for garage view)
// ─────────────────────────────────────────────────────────────────────────────

export async function getGarageRepairDetail(id: string) {
  const ctx = await requireAnyAuth();

  const [job] = await db
    .select({
      id: repairJobs.id,
      publicCode: repairJobs.publicCode,
      title: repairJobs.title,
      status: repairJobs.status,
      priority: repairJobs.priority,
      dueDate: repairJobs.dueDate,
      descriptionRaw: repairJobs.descriptionRaw,
      notesRaw: repairJobs.notesRaw,
      internalComments: repairJobs.internalComments,
      customerName: customers.name,
      customerId: repairJobs.customerId,
      customerPhone: customers.phone,
      customerEmail: customers.email,
      customerMobile: customers.mobile,
      unitRegistration: units.registration,
      unitBrand: units.brand,
      unitModel: units.model,
      unitId: repairJobs.unitId,
      unitYear: units.year,
      unitLength: units.length,
      unitChassisId: units.chassisId,
      unitStorageLocation: units.storageLocation,
      unitCurrentPosition: units.currentPosition,
      assignedUserName: users.name,
      assignedUserId: repairJobs.assignedUserId,
      finalCheckStatus: repairJobs.finalCheckStatus,
      finalCheckNotes: repairJobs.finalCheckNotes,
      // Flags
      waterDamageRiskFlag: repairJobs.waterDamageRiskFlag,
      safetyFlag: repairJobs.safetyFlag,
      tyresFlag: repairJobs.tyresFlag,
      lightsFlag: repairJobs.lightsFlag,
      brakesFlag: repairJobs.brakesFlag,
      windowsFlag: repairJobs.windowsFlag,
      sealsFlag: repairJobs.sealsFlag,
      partsRequiredFlag: repairJobs.partsRequiredFlag,
      followUpRequiredFlag: repairJobs.followUpRequiredFlag,
      customFlags: repairJobs.customFlags,
      // Admin messaging
      garageAdminMessage: repairJobs.garageAdminMessage,
      garageAdminMessageAt: repairJobs.garageAdminMessageAt,
      garageAdminMessageReadAt: repairJobs.garageAdminMessageReadAt,
    })
    .from(repairJobs)
    .leftJoin(customers, eq(repairJobs.customerId, customers.id))
    .leftJoin(units, eq(repairJobs.unitId, units.id))
    .leftJoin(users, eq(repairJobs.assignedUserId, users.id))
    .where(eq(repairJobs.id, id));

  if (!job) return null;

  const tasks = await db
    .select()
    .from(repairTasks)
    .where(eq(repairTasks.repairJobId, id))
    .orderBy(asc(repairTasks.sortOrder), asc(repairTasks.createdAt));

  const photos = await db
    .select()
    .from(repairPhotos)
    .where(eq(repairPhotos.repairJobId, id))
    .orderBy(desc(repairPhotos.createdAt));

  // Map OneDrive photos to use proxy URLs
  const mappedPhotos = photos.map((p) => {
    if (p.onedriveItemId && !p.url.startsWith("/api/photos/")) {
      return { ...p, url: `/api/photos/${p.id}`, thumbnailUrl: `/api/photos/${p.id}` };
    }
    return p;
  });

  // Fetch part requests for this repair
  const jobPartRequests = await db
    .select({
      id: partRequests.id,
      partName: partRequests.partName,
      quantity: partRequests.quantity,
      status: partRequests.status,
      expectedDelivery: partRequests.expectedDelivery,
      receivedDate: partRequests.receivedDate,
      notes: partRequests.notes,
      supplierName: suppliers.name,
    })
    .from(partRequests)
    .leftJoin(parts, eq(partRequests.partId, parts.id))
    .leftJoin(suppliers, eq(parts.supplierId, suppliers.id))
    .where(eq(partRequests.repairJobId, id))
    .orderBy(desc(partRequests.createdAt));

  // Fetch workers for this repair
  const jobWorkers = await db
    .select({
      id: repairWorkers.id,
      userId: repairWorkers.userId,
      userName: users.name,
      note: repairWorkers.note,
      createdAt: repairWorkers.createdAt,
    })
    .from(repairWorkers)
    .innerJoin(users, eq(repairWorkers.userId, users.id))
    .where(eq(repairWorkers.repairJobId, id))
    .orderBy(asc(repairWorkers.createdAt));

  return { ...job, tasks, photos: mappedPhotos, partRequests: jobPartRequests, workers: jobWorkers };
}

// ─────────────────────────────────────────────────────────────────────────────
// TASK STATUS UPDATE
// ─────────────────────────────────────────────────────────────────────────────

export async function updateTaskStatus(
  taskId: string,
  status: "pending" | "in_progress" | "done" | "problem" | "review",
  problemCategory?: string,
  problemNote?: string
) {
  const ctx = await requireAnyAuth();
  const userId = ctx.userId ?? null;

  const [task] = await db
    .select()
    .from(repairTasks)
    .where(eq(repairTasks.id, taskId));

  if (!task) throw new Error("Task not found");

  const updates: Record<string, unknown> = {
    status,
    updatedAt: new Date(),
  };

  if (status === "in_progress" && !task.startedAt) {
    updates.startedAt = new Date();
  }
  if (status === "done") {
    updates.completedAt = new Date();
    updates.completedByUserId = userId;
    updates.problemCategory = null;
    updates.problemNote = null;
  }
  if (status === "problem") {
    updates.problemCategory = problemCategory ?? "other";
    updates.problemNote = problemNote ?? null;
    updates.completedAt = null;
    updates.completedByUserId = null;
  }
  if (status === "pending") {
    updates.startedAt = null;
    updates.completedAt = null;
    updates.completedByUserId = null;
    updates.problemCategory = null;
    updates.problemNote = null;
  }

  await db.update(repairTasks).set(updates).where(eq(repairTasks.id, taskId));

  // Log event on the repair job
  await db.insert(repairJobEvents).values({
    repairJobId: task.repairJobId,
    userId,
    eventType: "task_status_changed",
    fieldChanged: "task_status",
    oldValue: task.status,
    newValue: status,
    comment: status === "problem"
      ? `Task "${task.title}" — Problem: ${problemCategory}${problemNote ? `. ${problemNote}` : ""}`
      : `Task "${task.title}" → ${status}`,
  });

  // Auto-update repair status based on task progress
  await autoUpdateRepairStatus(task.repairJobId);

  // Track sync state
  const syncType = status === "done" ? "task_completed" : status === "problem" ? "issue_reported" : "task_reopened";
  await recordGarageUpdate(task.repairJobId, syncType, userId);

  return { success: true };
}

// ─────────────────────────────────────────────────────────────────────────────
// AUTO STATUS: sync repair status based on task progress
// ─────────────────────────────────────────────────────────────────────────────

async function autoUpdateRepairStatus(repairJobId: string) {
  const tasks = await db
    .select({ status: repairTasks.status })
    .from(repairTasks)
    .where(eq(repairTasks.repairJobId, repairJobId));

  if (tasks.length === 0) return;

  const allDone = tasks.every((t) => t.status === "done");
  const anyInProgress = tasks.some((t) => t.status === "in_progress");
  const anyProblem = tasks.some((t) => t.status === "problem");

  const [job] = await db
    .select({ status: repairJobs.status })
    .from(repairJobs)
    .where(eq(repairJobs.id, repairJobId));

  if (!job) return;

  // Only auto-update if status is in a garage-relevant state
  const garageStatuses = ["scheduled", "in_progress", "blocked"];
  if (!garageStatuses.includes(job.status) && job.status !== "completed") return;

  if (allDone && job.status !== "completed") {
    await db
      .update(repairJobs)
      .set({
        status: "completed",
        completedAt: new Date(),
        finalCheckStatus: "pending",
        updatedAt: new Date(),
      })
      .where(eq(repairJobs.id, repairJobId));
  } else if (anyProblem && job.status !== "blocked") {
    await db
      .update(repairJobs)
      .set({ status: "blocked", updatedAt: new Date() })
      .where(eq(repairJobs.id, repairJobId));
  } else if (anyInProgress && job.status === "scheduled") {
    await db
      .update(repairJobs)
      .set({ status: "in_progress", updatedAt: new Date() })
      .where(eq(repairJobs.id, repairJobId));
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// GARAGE COMMENT (uses communication log)
// ─────────────────────────────────────────────────────────────────────────────

export async function addGarageComment(repairJobId: string, summary: string) {
  const ctx = await requireAnyAuth();

  // Capture the inserted id so callers can attach a voice note (or any
  // other side artefact) to this exact comment row.
  const [inserted] = await db
    .insert(communicationLogs)
    .values({
      repairJobId,
      userId: ctx.userId,
      contactMethod: "in_person",
      direction: "inbound",
      contactPerson: ctx.userName ?? "Garage",
      summary,
    })
    .returning({ id: communicationLogs.id });

  await db
    .update(repairJobs)
    .set({ lastContactAt: new Date(), updatedAt: new Date() })
    .where(eq(repairJobs.id, repairJobId));

  const [jobInfo] = await db
    .select({ publicCode: repairJobs.publicCode })
    .from(repairJobs)
    .where(eq(repairJobs.id, repairJobId));
  await notifyOffice(
    repairJobId,
    `💬 Garage opmerking — ${jobInfo?.publicCode ?? ""}`,
    summary,
    "garage_comment"
  );

  await recordGarageUpdate(repairJobId, "note_added", ctx.userId);

  return { success: true, id: inserted.id };
}

// ─────────────────────────────────────────────────────────────────────────────
// SUGGEST EXTRA TASK (from garage, not yet approved)
// ─────────────────────────────────────────────────────────────────────────────

export async function suggestExtraTask(
  repairJobId: string,
  title: string,
  description?: string,
  priority?: string
) {
  const ctx = await requireAnyAuth();

  // Get max sort order
  const [maxSort] = await db
    .select({ max: sql<number>`coalesce(max(${repairTasks.sortOrder}), 0)` })
    .from(repairTasks)
    .where(eq(repairTasks.repairJobId, repairJobId));

  const [task] = await db
    .insert(repairTasks)
    .values({
      repairJobId,
      title,
      description: description ?? null,
      source: "garage",
      sortOrder: (maxSort?.max ?? 0) + 1,
    })
    .returning();

  // Log event
  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: ctx.userId,
    eventType: "task_suggested",
    comment: `Garage suggested: "${title}"${description ? ` — ${description}` : ""}`,
  });

  // Notify office
  const [jobInfo] = await db
    .select({ publicCode: repairJobs.publicCode })
    .from(repairJobs)
    .where(eq(repairJobs.id, repairJobId));
  await notifyOffice(
    repairJobId,
    `➕ Garage taak voorstel — ${jobInfo?.publicCode ?? ""}`,
    `"${title}"${description ? `: ${description}` : ""}`,
    "garage_task_suggestion"
  );

  await recordGarageUpdate(repairJobId, "task_suggested", ctx.userId);

  return task;
}

// ─────────────────────────────────────────────────────────────────────────────
// SEARCH PARTS CATALOG (for garage picker)
// ─────────────────────────────────────────────────────────────────────────────

export async function searchPartsCatalog(query: string, category?: string) {
  await requireAnyAuth();

  const conditions = [];
  
  // Text search — only if query is non-empty
  if (query.trim()) {
    const q = `%${query.toLowerCase()}%`;
    conditions.push(
      sql`(lower(${parts.name}) like ${q} or lower(${parts.partNumber}) like ${q} or lower(${suppliers.name}) like ${q})`
    );
  }
  
  if (category) {
    conditions.push(sql`${parts.category} = ${category}`);
  }

  // Need at least one condition
  if (conditions.length === 0) return [];

  const results = await db
    .select({
      id: parts.id,
      name: parts.name,
      partNumber: parts.partNumber,
      category: parts.category,
      defaultCost: parts.defaultCost,
      markupPercent: parts.markupPercent,
      stockQuantity: parts.stockQuantity,
      supplierName: suppliers.name,
      supplierId: parts.supplierId,
    })
    .from(parts)
    .leftJoin(suppliers, eq(parts.supplierId, suppliers.id))
    .where(and(...conditions))
    .orderBy(
      query.trim()
        ? sql`CASE
            WHEN lower(${parts.name}) = ${query.toLowerCase()} THEN 0
            WHEN lower(${parts.partNumber}) = ${query.toLowerCase()} THEN 0
            WHEN lower(${parts.name}) like ${query.toLowerCase() + "%"} THEN 1
            ELSE 2
          END`
        : parts.name,
      parts.name
    )
    .limit(15);

  return results;
}

// ─────────────────────────────────────────────────────────────────────────────
// REQUEST PART (from garage — creates a part request + notifies office)
// ─────────────────────────────────────────────────────────────────────────────

export async function garageRequestPart(
  repairJobId: string,
  partName: string,
  options?: {
    partId?: string;
    quantity?: number;
    unitCost?: string;
    category?: string;
    requestType?: "part" | "equipment";
    workerName?: string;
  }
) {
  const ctx = await requireAnyAuth();
  const type = options?.requestType ?? "part";
  const isEquipment = type === "equipment";
  const requesterName = options?.workerName ?? ctx.userName ?? "technician";

  const [request] = await db
    .insert(partRequests)
    .values({
      repairJobId,
      partId: options?.partId ?? null,
      partName,
      quantity: options?.quantity ?? 1,
      unitCost: options?.unitCost ?? null,
      status: "requested",
      requestType: type,
      notes: `Requested by ${requesterName}`,
    })
    .returning();

  // Log event
  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: ctx.userId,
    eventType: "part_requested",
    comment: isEquipment
      ? `Garage requested equipment: "${partName}"`
      : `Garage requested part: "${partName}"`,
  });

  // Notify office
  const [jobInfo] = await db
    .select({ publicCode: repairJobs.publicCode })
    .from(repairJobs)
    .where(eq(repairJobs.id, repairJobId));
  await notifyOffice(
    repairJobId,
    isEquipment
      ? `🔧 Gereedschap aangevraagd — ${jobInfo?.publicCode ?? ""}`
      : `📦 Onderdeel aangevraagd — ${jobInfo?.publicCode ?? ""}`,
    `"${partName}"`,
    "garage_part_request"
  );

  safeRevalidate(`/garage/repairs/${repairJobId}`);
  safeRevalidate(`/repairs/${repairJobId}`);
  safeRevalidate("/parts");

  await recordGarageUpdate(repairJobId, "part_requested", ctx.userId);

  return request;
}

// ─────────────────────────────────────────────────────────────────────────────
// MARK PART RECEIVED (garage-callable; mirrors admin updatePartRequestStatus)
// ─────────────────────────────────────────────────────────────────────────────

export async function garageMarkPartReceived(partRequestId: string) {
  const ctx = await requireAnyAuth();

  const [pr] = await db
    .update(partRequests)
    .set({ status: "received", receivedDate: new Date(), updatedAt: new Date() })
    .where(eq(partRequests.id, partRequestId))
    .returning({
      repairJobId: partRequests.repairJobId,
      partName: partRequests.partName,
    });

  if (!pr || !pr.repairJobId) return { success: true };

  // If all non-equipment parts are now received and the repair was in
  // waiting_parts, flip back to todo so it shows up as actionable again.
  const [pendingRow] = await db
    .select({ count: sql<number>`count(*)` })
    .from(partRequests)
    .where(
      and(
        eq(partRequests.repairJobId, pr.repairJobId),
        sql`${partRequests.status} in ('requested', 'ordered', 'shipped')`,
      ),
    );
  if (Number(pendingRow?.count ?? 0) === 0) {
    const [job] = await db
      .select({ status: repairJobs.status })
      .from(repairJobs)
      .where(eq(repairJobs.id, pr.repairJobId));
    if (job?.status === "waiting_parts") {
      await db
        .update(repairJobs)
        .set({ status: "todo", updatedAt: new Date() })
        .where(eq(repairJobs.id, pr.repairJobId));
    }
  }

  // Audit + notify office so admins see the part has landed.
  await db.insert(repairJobEvents).values({
    repairJobId: pr.repairJobId,
    userId: ctx.userId,
    eventType: "part_received",
    fieldChanged: "part_request_status",
    newValue: "received",
    comment: `Part received in garage: "${pr.partName}"`,
  });

  const [jobInfo] = await db
    .select({ publicCode: repairJobs.publicCode })
    .from(repairJobs)
    .where(eq(repairJobs.id, pr.repairJobId));
  await notifyOffice(
    pr.repairJobId,
    `📦 Part received — ${jobInfo?.publicCode ?? ""}`,
    `"${pr.partName}"`,
    "garage_part_received",
  );

  await recordGarageUpdate(pr.repairJobId, "part_received", ctx.userId);

  safeRevalidate(`/garage/repairs/${pr.repairJobId}`);
  safeRevalidate(`/repairs/${pr.repairJobId}`);
  safeRevalidate("/parts");

  return { success: true };
}

// ─────────────────────────────────────────────────────────────────────────────
// FINAL CHECK
// ─────────────────────────────────────────────────────────────────────────────

export async function completeFinalCheck(repairJobId: string, notes?: string) {
  const ctx = await requireAnyAuth();

  await db
    .update(repairJobs)
    .set({
      finalCheckStatus: "passed",
      finalCheckByUserId: ctx.userId,
      finalCheckAt: new Date(),
      finalCheckNotes: notes ?? null,
      updatedAt: new Date(),
    })
    .where(eq(repairJobs.id, repairJobId));

  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: ctx.userId,
    eventType: "final_check_passed",
    comment: notes ? `Final check passed. ${notes}` : "Final check passed.",
  });

  return { success: true };
}

export async function failFinalCheck(repairJobId: string, notes: string) {
  const ctx = await requireAnyAuth();

  await db
    .update(repairJobs)
    .set({
      finalCheckStatus: "failed",
      finalCheckByUserId: ctx.userId,
      finalCheckAt: new Date(),
      finalCheckNotes: notes,
      status: "in_progress",
      completedAt: null,
      updatedAt: new Date(),
    })
    .where(eq(repairJobs.id, repairJobId));

  // Reset all "done" tasks back to "review" so garage re-checks
  await db
    .update(repairTasks)
    .set({ status: "review", updatedAt: new Date() })
    .where(
      and(
        eq(repairTasks.repairJobId, repairJobId),
        eq(repairTasks.status, "done")
      )
    );

  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: ctx.userId,
    eventType: "final_check_failed",
    comment: `Final check failed: ${notes}`,
  });

  return { success: true };
}

// ─────────────────────────────────────────────────────────────────────────────
// TASK MANAGEMENT (from office)
// ─────────────────────────────────────────────────────────────────────────────

export async function addRepairTask(
  repairJobId: string,
  data: {
    title: string;
    titleEs?: string;
    titleNl?: string;
    description?: string;
    estimatedHours?: number;
    hourlyRate?: number;
    billable?: boolean;
    includeInEstimate?: boolean;
  }
) {
  const ctx = await requireAnyAuth();

  const [maxSort] = await db
    .select({ max: sql<number>`coalesce(max(${repairTasks.sortOrder}), 0)` })
    .from(repairTasks)
    .where(eq(repairTasks.repairJobId, repairJobId));

  const [task] = await db
    .insert(repairTasks)
    .values({
      repairJobId,
      title: data.title,
      titleEs: data.titleEs ?? null,
      titleNl: data.titleNl ?? null,
      description: data.description ?? null,
      estimatedHours: data.estimatedHours != null ? String(data.estimatedHours) : null,
      hourlyRate: data.hourlyRate != null ? String(data.hourlyRate) : null,
      billable: data.billable ?? true,
      includeInEstimate: data.includeInEstimate ?? true,
      source: "office",
      sortOrder: (maxSort?.max ?? 0) + 1,
      approvedAt: new Date(),
    })
    .returning();

  return task;
}

export async function deleteRepairTask(taskId: string) {
  const ctx = await requireAnyAuth();

  const [task] = await db
    .select({ repairJobId: repairTasks.repairJobId, title: repairTasks.title })
    .from(repairTasks)
    .where(eq(repairTasks.id, taskId));

  if (!task) throw new Error("Task not found");

  await db.delete(repairTasks).where(eq(repairTasks.id, taskId));

  await db.insert(repairJobEvents).values({
    repairJobId: task.repairJobId,
    userId: ctx.userId,
    eventType: "task_deleted",
    comment: `Task removed: "${task.title}"`,
  });

  return { success: true };
}

export async function approveGarageTask(taskId: string) {
  const ctx = await requireAnyAuth();

  await db
    .update(repairTasks)
    .set({
      approvedAt: new Date(),
      approvedByUserId: ctx.userId,
      updatedAt: new Date(),
    })
    .where(eq(repairTasks.id, taskId));

  return { success: true };
}

export async function getRepairTasks(repairJobId: string) {
  await requireAnyAuth();
  return db
    .select()
    .from(repairTasks)
    .where(eq(repairTasks.repairJobId, repairJobId))
    .orderBy(asc(repairTasks.sortOrder), asc(repairTasks.createdAt));
}

export async function updateRepairTaskPricing(
  taskId: string,
  data: {
    estimatedHours?: number | null;
    actualHours?: number | null;
    hourlyRate?: number | null;
    billable?: boolean;
    includeInEstimate?: boolean;
  }
) {
  await requireAnyAuth();
  const updates: Record<string, unknown> = { updatedAt: new Date() };
  if (data.estimatedHours !== undefined) updates.estimatedHours = data.estimatedHours != null ? String(data.estimatedHours) : null;
  if (data.actualHours !== undefined) updates.actualHours = data.actualHours != null ? String(data.actualHours) : null;
  if (data.hourlyRate !== undefined) updates.hourlyRate = data.hourlyRate != null ? String(data.hourlyRate) : null;
  if (data.billable !== undefined) updates.billable = data.billable;
  if (data.includeInEstimate !== undefined) updates.includeInEstimate = data.includeInEstimate;
  await db.update(repairTasks).set(updates).where(eq(repairTasks.id, taskId));
  safeRevalidate("/");
}

// ─────────────────────────────────────────────────────────────────────────────
// REPAIR WORKERS (who worked on a repair)
// ─────────────────────────────────────────────────────────────────────────────

export async function getRepairWorkers(repairJobId: string) {
  await requireAnyAuth();
  return db
    .select({
      id: repairWorkers.id,
      userId: repairWorkers.userId,
      userName: users.name,
      note: repairWorkers.note,
      createdAt: repairWorkers.createdAt,
    })
    .from(repairWorkers)
    .innerJoin(users, eq(repairWorkers.userId, users.id))
    .where(eq(repairWorkers.repairJobId, repairJobId))
    .orderBy(asc(repairWorkers.createdAt));
}

/** Toggle worker assignment — adds or removes the specified (or current) user */
export async function toggleMyWorker(repairJobId: string, targetUserId?: string) {
  const ctx = await requireAnyAuth();
  const userId = targetUserId ?? ctx.userId;
  if (!userId) throw new Error("User identity required");

  const existing = await db
    .select({ id: repairWorkers.id })
    .from(repairWorkers)
    .where(and(eq(repairWorkers.repairJobId, repairJobId), eq(repairWorkers.userId, userId)));

  if (existing.length > 0) {
    await db.delete(repairWorkers).where(eq(repairWorkers.id, existing[0].id));
  } else {
    await db.insert(repairWorkers).values({
      repairJobId,
      userId,
      addedByUserId: ctx.userId ?? userId,
    });
  }

  safeRevalidate(`/garage/repairs/${repairJobId}`);
  safeRevalidate(`/repairs/${repairJobId}`);
}

/** Admin/staff: add a worker to a repair */
export async function addRepairWorker(repairJobId: string, userId: string) {
  const ctx = await requireAnyAuth();

  // Check not already added
  const existing = await db
    .select({ id: repairWorkers.id })
    .from(repairWorkers)
    .where(and(eq(repairWorkers.repairJobId, repairJobId), eq(repairWorkers.userId, userId)));

  if (existing.length > 0) return;

  await db.insert(repairWorkers).values({
    repairJobId,
    userId,
    addedByUserId: ctx.userId,
  });

  safeRevalidate(`/repairs/${repairJobId}`);
}

/** Admin/staff: remove a worker from a repair */
export async function removeRepairWorker(repairJobId: string, userId: string) {
  await requireAnyAuth();
  await db.delete(repairWorkers).where(
    and(eq(repairWorkers.repairJobId, repairJobId), eq(repairWorkers.userId, userId))
  );
  safeRevalidate(`/repairs/${repairJobId}`);
}

/** Update a worker's note */
export async function updateWorkerNote(workerId: string, note: string) {
  await requireAnyAuth();
  await db.update(repairWorkers).set({ note: note || null }).where(eq(repairWorkers.id, workerId));
}

/** Get all active users (for worker assignment dropdown) */
export async function getActiveUsers() {
  await requireAnyAuth();
  return db
    .select({
      id: users.id,
      name: users.name,
      role: users.role,
      preferredLanguage: users.preferredLanguage,
    })
    .from(users)
    .where(eq(users.active, true))
    .orderBy(users.name);
}

/**
 * Updates a technician's UI/notification language preference. Used by
 * the small "your language" picker in the garage when a worker prefers
 * a different language than the auto-seeded one. Anyone holding the
 * shared garage PIN can update any technician's language — this is a
 * shared workshop tool, not a per-user account.
 */
export async function setUserPreferredLanguage(
  userId: string,
  language: "en" | "es" | "nl",
) {
  await requireAnyAuth();
  await db
    .update(users)
    .set({ preferredLanguage: language, updatedAt: new Date() })
    .where(eq(users.id, userId));
  return { ok: true as const };
}

// ─────────────────────────────────────────────────────────────────────────────
// FINDINGS: technicians log inspection findings
// ─────────────────────────────────────────────────────────────────────────────

export async function addFinding(
  repairJobId: string,
  data: {
    category: string;
    description: string;
    severity: string;
    requiresFollowUp?: boolean;
    requiresCustomerApproval?: boolean;
  }
) {
  const ctx = await requireAnyAuth();

  const [finding] = await db
    .insert(repairFindings)
    .values({
      repairJobId,
      category: data.category as any,
      description: data.description,
      severity: data.severity as any,
      requiresFollowUp: data.requiresFollowUp ?? false,
      requiresCustomerApproval: data.requiresCustomerApproval ?? false,
      createdByUserId: ctx.userId,
    })
    .returning();

  // Log timeline event
  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: ctx.userId,
    eventType: "finding_added",
    comment: `${data.severity} finding (${data.category}): ${data.description}`,
  });

  // Auto-behaviors based on severity/flags
  if (data.severity === "critical") {
    // Auto-escalate priority to high if currently normal or low
    const [job] = await db
      .select({ priority: repairJobs.priority })
      .from(repairJobs)
      .where(eq(repairJobs.id, repairJobId));
    if (job && (job.priority === "normal" || job.priority === "low")) {
      await db
        .update(repairJobs)
        .set({ priority: "high", updatedAt: new Date() })
        .where(eq(repairJobs.id, repairJobId));
    }
    await notifyOffice(
      repairJobId,
      `⚠️ Critical finding: ${data.description}`,
      `Category: ${data.category}, Severity: CRITICAL`,
      "garage_critical_finding"
    );
  }

  if (data.requiresCustomerApproval) {
    await db
      .update(repairJobs)
      .set({
        customerResponseStatus: "waiting_response",
        updatedAt: new Date(),
      })
      .where(eq(repairJobs.id, repairJobId));
    await notifyOffice(
      repairJobId,
      `Customer approval required: ${data.description}`,
      `Category: ${data.category}`,
      "garage_approval_needed"
    );
  } else if (data.severity !== "critical") {
    await notifyOffice(
      repairJobId,
      `Finding logged: ${data.description}`,
      `Category: ${data.category}, Severity: ${data.severity}`,
      "garage_finding"
    );
  }

  // Set relevant flags based on category
  const flagMap: Record<string, Record<string, boolean>> = {
    water_damage: { waterDamageRiskFlag: true },
    tyres: { tyresFlag: true },
    lighting: { lightsFlag: true },
    brakes: { brakesFlag: true },
    windows: { windowsFlag: true },
    seals: { sealsFlag: true },
  };
  const flagUpdate = flagMap[data.category];
  if (flagUpdate) {
    await db
      .update(repairJobs)
      .set({ ...flagUpdate, updatedAt: new Date() })
      .where(eq(repairJobs.id, repairJobId));
  }

  if (data.requiresFollowUp) {
    await db
      .update(repairJobs)
      .set({ followUpRequiredFlag: true, updatedAt: new Date() })
      .where(eq(repairJobs.id, repairJobId));
  }

  safeRevalidate(`/garage/repairs/${repairJobId}`);
  safeRevalidate(`/repairs/${repairJobId}`);

  const syncType = data.severity === "critical" ? "urgent_issue" : "issue_reported";
  await recordGarageUpdate(repairJobId, syncType, ctx.userId);

  return finding;
}

export async function getRepairFindings(repairJobId: string) {
  await requireAnyAuth();
  return db
    .select({
      id: repairFindings.id,
      category: repairFindings.category,
      description: repairFindings.description,
      severity: repairFindings.severity,
      requiresFollowUp: repairFindings.requiresFollowUp,
      requiresCustomerApproval: repairFindings.requiresCustomerApproval,
      resolvedAt: repairFindings.resolvedAt,
      createdAt: repairFindings.createdAt,
      createdByName: users.name,
    })
    .from(repairFindings)
    .leftJoin(users, eq(repairFindings.createdByUserId, users.id))
    .where(eq(repairFindings.repairJobId, repairJobId))
    .orderBy(desc(repairFindings.createdAt));
}

export async function resolveFinding(findingId: string) {
  await requireAnyAuth();
  await db
    .update(repairFindings)
    .set({ resolvedAt: new Date() })
    .where(eq(repairFindings.id, findingId));
  safeRevalidate("/");
}

export async function deleteFinding(findingId: string) {
  await requireRole("admin");
  await db.delete(repairFindings).where(eq(repairFindings.id, findingId));
  safeRevalidate("/");
}

// ─────────────────────────────────────────────────────────────────────────────
// BLOCKERS: job-level blockers
// ─────────────────────────────────────────────────────────────────────────────

export async function addBlocker(
  repairJobId: string,
  data: { reason: string; description?: string }
) {
  const ctx = await requireAnyAuth();

  const [blocker] = await db
    .insert(repairBlockers)
    .values({
      repairJobId,
      reason: data.reason as any,
      description: data.description ?? null,
      createdByUserId: ctx.userId,
    })
    .returning();

  // Log timeline event
  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: ctx.userId,
    eventType: "blocker_added",
    comment: `Blocker: ${data.reason}${data.description ? ` — ${data.description}` : ""}`,
  });

  // Auto-update repair status based on blocker reason
  const statusMap: Record<string, string> = {
    waiting_parts: "waiting_parts",
    waiting_customer: "waiting_customer",
  };
  const newStatus = statusMap[data.reason] ?? "blocked";
  await db
    .update(repairJobs)
    .set({
      status: newStatus as any,
      currentBlocker: data.description || data.reason,
      updatedAt: new Date(),
    })
    .where(eq(repairJobs.id, repairJobId));

  // Update customer response status for waiting_customer
  if (data.reason === "waiting_customer") {
    await db
      .update(repairJobs)
      .set({ customerResponseStatus: "waiting_response" })
      .where(eq(repairJobs.id, repairJobId));
  }

  // Parts required flag for waiting_parts
  if (data.reason === "waiting_parts") {
    await db
      .update(repairJobs)
      .set({ partsRequiredFlag: true })
      .where(eq(repairJobs.id, repairJobId));
  }

  await notifyOffice(
    repairJobId,
    `🚫 Blocker: ${data.reason}`,
    data.description ?? undefined,
    "garage_blocker"
  );

  safeRevalidate(`/garage/repairs/${repairJobId}`);
  safeRevalidate(`/repairs/${repairJobId}`);

  await recordGarageUpdate(repairJobId, "blocker_added", ctx.userId);

  return blocker;
}

export async function resolveBlocker(blockerId: string) {
  const ctx = await requireAnyAuth();

  const [blocker] = await db
    .select({
      repairJobId: repairBlockers.repairJobId,
      reason: repairBlockers.reason,
    })
    .from(repairBlockers)
    .where(eq(repairBlockers.id, blockerId));

  if (!blocker) throw new Error("Blocker not found");

  await db
    .update(repairBlockers)
    .set({
      active: false,
      resolvedAt: new Date(),
      resolvedByUserId: ctx.userId,
    })
    .where(eq(repairBlockers.id, blockerId));

  // Log event
  await db.insert(repairJobEvents).values({
    repairJobId: blocker.repairJobId,
    userId: ctx.userId,
    eventType: "blocker_resolved",
    comment: `Blocker resolved: ${blocker.reason}`,
  });

  // Check if there are other active blockers
  const [remaining] = await db
    .select({ cnt: count() })
    .from(repairBlockers)
    .where(
      and(
        eq(repairBlockers.repairJobId, blocker.repairJobId),
        eq(repairBlockers.active, true)
      )
    );

  // If no more active blockers, move back to in_progress
  if (!remaining || remaining.cnt === 0) {
    await db
      .update(repairJobs)
      .set({
        status: "in_progress",
        currentBlocker: null,
        updatedAt: new Date(),
      })
      .where(eq(repairJobs.id, blocker.repairJobId));
  }

  safeRevalidate(`/garage/repairs/${blocker.repairJobId}`);
  safeRevalidate(`/repairs/${blocker.repairJobId}`);
}

export async function getRepairBlockers(repairJobId: string) {
  await requireAnyAuth();
  return db
    .select({
      id: repairBlockers.id,
      reason: repairBlockers.reason,
      description: repairBlockers.description,
      active: repairBlockers.active,
      createdAt: repairBlockers.createdAt,
      resolvedAt: repairBlockers.resolvedAt,
      createdByName: users.name,
    })
    .from(repairBlockers)
    .leftJoin(users, eq(repairBlockers.createdByUserId, users.id))
    .where(eq(repairBlockers.repairJobId, repairJobId))
    .orderBy(desc(repairBlockers.active), desc(repairBlockers.createdAt));
}

// ─────────────────────────────────────────────────────────────────────────────
// QUICK STATS (for empty state / dashboard strip)
// ─────────────────────────────────────────────────────────────────────────────

export async function getGarageQuickStats() {
  await requireAnyAuth();

  const now = new Date();

  // Tomorrow range
  const tomorrowStart = new Date(now);
  tomorrowStart.setDate(tomorrowStart.getDate() + 1);
  tomorrowStart.setHours(0, 0, 0, 0);
  const tomorrowEnd = new Date(tomorrowStart);
  tomorrowEnd.setHours(23, 59, 59, 999);

  const [tomorrowJobs] = await db
    .select({ count: count() })
    .from(repairJobs)
    .where(
      and(
        isNull(repairJobs.deletedAt),
        isNull(repairJobs.archivedAt),
        gte(repairJobs.dueDate, tomorrowStart),
        lte(repairJobs.dueDate, tomorrowEnd)
      )
    );

  // Waiting parts (any active job with pending parts)
  const [waitingParts] = await db
    .select({ count: count() })
    .from(repairJobs)
    .where(
      and(
        isNull(repairJobs.deletedAt),
        isNull(repairJobs.archivedAt),
        eq(repairJobs.status, "waiting_parts")
      )
    );

  // Urgent/high priority active jobs
  const [urgentJobs] = await db
    .select({ count: count() })
    .from(repairJobs)
    .where(
      and(
        isNull(repairJobs.deletedAt),
        isNull(repairJobs.archivedAt),
        inArray(repairJobs.priority, ["urgent", "high"]),
        inArray(repairJobs.status, [
          "new", "todo", "scheduled", "in_progress", "waiting_parts", "waiting_customer",
        ])
      )
    );

  // Unassigned active jobs
  const [unassigned] = await db
    .select({ count: count() })
    .from(repairJobs)
    .where(
      and(
        isNull(repairJobs.deletedAt),
        isNull(repairJobs.archivedAt),
        isNull(repairJobs.assignedUserId),
        inArray(repairJobs.status, [
          "new", "todo", "scheduled", "in_progress",
        ])
      )
    );

  return {
    tomorrowCount: Number(tomorrowJobs.count),
    waitingPartsCount: Number(waitingParts.count),
    urgentCount: Number(urgentJobs.count),
    unassignedCount: Number(unassigned.count),
  };
}
