"use server";

import { db } from "@/lib/db";
import { repairJobs, repairTasks, repairPhotos, customers, units, users, repairJobEvents, communicationLogs, actionReminders, partRequests, parts, suppliers, repairWorkers, repairFindings, repairBlockers } from "@/lib/db/schema";
import { requireAuth, requireRole } from "@/lib/auth-utils";
import { eq, and, isNull, gte, lte, desc, asc, count, sql, inArray } from "drizzle-orm";
import { revalidatePath } from "next/cache";

// ─────────────────────────────────────────────────────────────────────────────
// HELPER: create office notification for garage activity
// ─────────────────────────────────────────────────────────────────────────────

async function notifyOffice(
  repairJobId: string,
  title: string,
  description?: string,
  triggerEvent?: string
) {
  await db.insert(actionReminders).values({
    repairJobId,
    reminderType: "custom",
    title,
    description: description ?? null,
    autoGenerated: true,
    triggerEvent: triggerEvent ?? "garage_feedback",
  });
  revalidatePath("/");
}

// ─────────────────────────────────────────────────────────────────────────────
// AUTO START: move to in_progress when a technician opens the repair
// ─────────────────────────────────────────────────────────────────────────────

const autoStartStatuses = ["new", "todo", "scheduled"];

export async function garageAutoStart(repairJobId: string) {
  const session = await requireAuth();

  const [job] = await db
    .select({ status: repairJobs.status })
    .from(repairJobs)
    .where(eq(repairJobs.id, repairJobId));

  if (!job || !autoStartStatuses.includes(job.status)) return { changed: false };

  await db
    .update(repairJobs)
    .set({ status: "in_progress", updatedAt: new Date() })
    .where(eq(repairJobs.id, repairJobId));

  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: session.user.id,
    eventType: "status_changed",
    fieldChanged: "status",
    oldValue: job.status,
    newValue: "in_progress",
    comment: "Auto-started when opened in garage",
  });

  return { changed: true };
}

// ─────────────────────────────────────────────────────────────────────────────
// UPDATE TITLE (from garage)
// ─────────────────────────────────────────────────────────────────────────────

export async function updateRepairTitle(repairJobId: string, title: string) {
  const session = await requireAuth();
  const trimmed = title.trim();
  if (!trimmed) throw new Error("Title cannot be empty");

  await db
    .update(repairJobs)
    .set({ title: trimmed, updatedAt: new Date() })
    .where(eq(repairJobs.id, repairJobId));

  return { success: true };
}

// ─────────────────────────────────────────────────────────────────────────────
// MARK DONE / NOT DONE (from garage)
// ─────────────────────────────────────────────────────────────────────────────

export async function garageMarkDone(repairJobId: string) {
  const session = await requireAuth();

  await db
    .update(repairJobs)
    .set({
      status: "completed",
      completedAt: new Date(),
      finalCheckStatus: "pending",
      updatedAt: new Date(),
    })
    .where(eq(repairJobs.id, repairJobId));

  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: session.user.id,
    eventType: "status_changed",
    fieldChanged: "status",
    newValue: "completed",
    comment: "Marked as done by garage",
  });

  // Notify office
  const [jobInfo] = await db
    .select({ publicCode: repairJobs.publicCode })
    .from(repairJobs)
    .where(eq(repairJobs.id, repairJobId));
  await notifyOffice(
    repairJobId,
    `✅ Garage klaar — ${jobInfo?.publicCode ?? ""}`,
    "Reparatie is door de garage als klaar gemeld",
    "garage_done"
  );

  return { success: true };
}

export async function garageMarkNotDone(repairJobId: string, reason: string) {
  const session = await requireAuth();
  const trimmed = reason.trim();
  if (!trimmed) throw new Error("Reason is required");

  // Set status to blocked
  await db
    .update(repairJobs)
    .set({ status: "blocked", updatedAt: new Date() })
    .where(eq(repairJobs.id, repairJobId));

  // Log as event (visible in office timeline)
  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: session.user.id,
    eventType: "status_changed",
    fieldChanged: "status",
    newValue: "blocked",
    comment: `Garage: niet klaar — ${trimmed}`,
  });

  // Also add as communication log (visible in office)
  await db.insert(communicationLogs).values({
    repairJobId,
    userId: session.user.id,
    contactMethod: "in_person",
    direction: "inbound",
    contactPerson: session.user.name ?? "Garage",
    summary: `⚠️ Niet klaar: ${trimmed}`,
  });

  await db
    .update(repairJobs)
    .set({ lastContactAt: new Date() })
    .where(eq(repairJobs.id, repairJobId));

  // Notify office
  const [jobInfo] = await db
    .select({ publicCode: repairJobs.publicCode })
    .from(repairJobs)
    .where(eq(repairJobs.id, repairJobId));
  await notifyOffice(
    repairJobId,
    `🔧 Garage: niet klaar — ${jobInfo?.publicCode ?? ""}`,
    trimmed,
    "garage_not_done"
  );

  return { success: true };
}

// ─────────────────────────────────────────────────────────────────────────────
// TODAY's REPAIRS
// ─────────────────────────────────────────────────────────────────────────────

export async function getGarageRepairsToday() {
  const session = await requireAuth();

  const now = new Date();
  const startOfDay = new Date(now);
  startOfDay.setHours(0, 0, 0, 0);
  const endOfDay = new Date(now);
  endOfDay.setHours(23, 59, 59, 999);

  const jobs = await db
    .select({
      id: repairJobs.id,
      publicCode: repairJobs.publicCode,
      title: repairJobs.title,
      status: repairJobs.status,
      priority: repairJobs.priority,
      dueDate: repairJobs.dueDate,
      customerName: customers.name,
      unitRegistration: units.registration,
      unitBrand: units.brand,
      unitModel: units.model,
      unitStorageLocation: units.storageLocation,
      unitCurrentPosition: units.currentPosition,
      assignedUserName: users.name,
      finalCheckStatus: repairJobs.finalCheckStatus,
      jobType: repairJobs.jobType,
    })
    .from(repairJobs)
    .leftJoin(customers, eq(repairJobs.customerId, customers.id))
    .leftJoin(units, eq(repairJobs.unitId, units.id))
    .leftJoin(users, eq(repairJobs.assignedUserId, users.id))
    .where(
      and(
        isNull(repairJobs.deletedAt),
        isNull(repairJobs.archivedAt),
        gte(repairJobs.dueDate, startOfDay),
        lte(repairJobs.dueDate, endOfDay)
      )
    )
    .orderBy(asc(repairJobs.priority), asc(repairJobs.title));

  // Get task counts per job
  const jobIds = jobs.map((j) => j.id);
  if (jobIds.length === 0) return [];

  const taskCounts = await db
    .select({
      repairJobId: repairTasks.repairJobId,
      total: count(),
      done: sql<number>`count(*) filter (where ${repairTasks.status} = 'done')`,
      problem: sql<number>`count(*) filter (where ${repairTasks.status} = 'problem')`,
    })
    .from(repairTasks)
    .groupBy(repairTasks.repairJobId);

  const countsMap = new Map(
    taskCounts.map((c) => [
      c.repairJobId,
      { total: Number(c.total), done: Number(c.done), problem: Number(c.problem) },
    ])
  );

  // Get part request counts per job
  const partCounts = await db
    .select({
      repairJobId: partRequests.repairJobId,
      total: count(),
      received: sql<number>`count(*) filter (where ${partRequests.status} = 'received')`,
      pending: sql<number>`count(*) filter (where ${partRequests.status} in ('requested', 'ordered', 'shipped'))`,
    })
    .from(partRequests)
    .groupBy(partRequests.repairJobId);

  const partsMap = new Map(
    partCounts.map((c) => [
      c.repairJobId,
      { total: Number(c.total), received: Number(c.received), pending: Number(c.pending) },
    ])
  );

  // Get workers per job
  const workers = await db
    .select({
      repairJobId: repairWorkers.repairJobId,
      userName: users.name,
    })
    .from(repairWorkers)
    .innerJoin(users, eq(repairWorkers.userId, users.id))
    .where(inArray(repairWorkers.repairJobId, jobIds));

  const workersMap = new Map<string, string[]>();
  for (const w of workers) {
    const list = workersMap.get(w.repairJobId) ?? [];
    list.push(w.userName);
    workersMap.set(w.repairJobId, list);
  }

  return jobs.map((job) => ({
    ...job,
    tasks: countsMap.get(job.id) ?? { total: 0, done: 0, problem: 0 },
    parts: partsMap.get(job.id) ?? { total: 0, received: 0, pending: 0 },
    workers: workersMap.get(job.id) ?? [],
  }));
}

// ─────────────────────────────────────────────────────────────────────────────
// REPAIR DETAIL (for garage view)
// ─────────────────────────────────────────────────────────────────────────────

export async function getGarageRepairDetail(id: string) {
  const session = await requireAuth();

  const [job] = await db
    .select({
      id: repairJobs.id,
      publicCode: repairJobs.publicCode,
      title: repairJobs.title,
      status: repairJobs.status,
      priority: repairJobs.priority,
      dueDate: repairJobs.dueDate,
      descriptionRaw: repairJobs.descriptionRaw,
      notesRaw: repairJobs.notesRaw,
      internalComments: repairJobs.internalComments,
      customerName: customers.name,
      customerId: repairJobs.customerId,
      customerPhone: customers.phone,
      customerEmail: customers.email,
      customerMobile: customers.mobile,
      unitRegistration: units.registration,
      unitBrand: units.brand,
      unitModel: units.model,
      unitId: repairJobs.unitId,
      unitYear: units.year,
      unitLength: units.length,
      unitChassisId: units.chassisId,
      unitStorageLocation: units.storageLocation,
      unitCurrentPosition: units.currentPosition,
      assignedUserName: users.name,
      assignedUserId: repairJobs.assignedUserId,
      finalCheckStatus: repairJobs.finalCheckStatus,
      finalCheckNotes: repairJobs.finalCheckNotes,
      // Flags
      waterDamageRiskFlag: repairJobs.waterDamageRiskFlag,
      safetyFlag: repairJobs.safetyFlag,
      tyresFlag: repairJobs.tyresFlag,
      lightsFlag: repairJobs.lightsFlag,
      brakesFlag: repairJobs.brakesFlag,
      windowsFlag: repairJobs.windowsFlag,
      sealsFlag: repairJobs.sealsFlag,
      partsRequiredFlag: repairJobs.partsRequiredFlag,
      followUpRequiredFlag: repairJobs.followUpRequiredFlag,
    })
    .from(repairJobs)
    .leftJoin(customers, eq(repairJobs.customerId, customers.id))
    .leftJoin(units, eq(repairJobs.unitId, units.id))
    .leftJoin(users, eq(repairJobs.assignedUserId, users.id))
    .where(eq(repairJobs.id, id));

  if (!job) return null;

  const tasks = await db
    .select()
    .from(repairTasks)
    .where(eq(repairTasks.repairJobId, id))
    .orderBy(asc(repairTasks.sortOrder), asc(repairTasks.createdAt));

  const photos = await db
    .select()
    .from(repairPhotos)
    .where(eq(repairPhotos.repairJobId, id))
    .orderBy(desc(repairPhotos.createdAt));

  // Fetch part requests for this repair
  const jobPartRequests = await db
    .select({
      id: partRequests.id,
      partName: partRequests.partName,
      quantity: partRequests.quantity,
      status: partRequests.status,
      expectedDelivery: partRequests.expectedDelivery,
      receivedDate: partRequests.receivedDate,
      notes: partRequests.notes,
      supplierName: suppliers.name,
    })
    .from(partRequests)
    .leftJoin(parts, eq(partRequests.partId, parts.id))
    .leftJoin(suppliers, eq(parts.supplierId, suppliers.id))
    .where(eq(partRequests.repairJobId, id))
    .orderBy(desc(partRequests.createdAt));

  // Fetch workers for this repair
  const jobWorkers = await db
    .select({
      id: repairWorkers.id,
      userId: repairWorkers.userId,
      userName: users.name,
      note: repairWorkers.note,
      createdAt: repairWorkers.createdAt,
    })
    .from(repairWorkers)
    .innerJoin(users, eq(repairWorkers.userId, users.id))
    .where(eq(repairWorkers.repairJobId, id))
    .orderBy(asc(repairWorkers.createdAt));

  return { ...job, tasks, photos, partRequests: jobPartRequests, workers: jobWorkers };
}

// ─────────────────────────────────────────────────────────────────────────────
// TASK STATUS UPDATE
// ─────────────────────────────────────────────────────────────────────────────

export async function updateTaskStatus(
  taskId: string,
  status: "pending" | "in_progress" | "done" | "problem" | "review",
  problemCategory?: string,
  problemNote?: string
) {
  const session = await requireAuth();
  const userId = session.user.id;

  const [task] = await db
    .select()
    .from(repairTasks)
    .where(eq(repairTasks.id, taskId));

  if (!task) throw new Error("Task not found");

  const updates: Record<string, unknown> = {
    status,
    updatedAt: new Date(),
  };

  if (status === "in_progress" && !task.startedAt) {
    updates.startedAt = new Date();
  }
  if (status === "done") {
    updates.completedAt = new Date();
    updates.completedByUserId = userId;
    updates.problemCategory = null;
    updates.problemNote = null;
  }
  if (status === "problem") {
    updates.problemCategory = problemCategory ?? "other";
    updates.problemNote = problemNote ?? null;
    updates.completedAt = null;
    updates.completedByUserId = null;
  }
  if (status === "pending") {
    updates.startedAt = null;
    updates.completedAt = null;
    updates.completedByUserId = null;
    updates.problemCategory = null;
    updates.problemNote = null;
  }

  await db.update(repairTasks).set(updates).where(eq(repairTasks.id, taskId));

  // Log event on the repair job
  await db.insert(repairJobEvents).values({
    repairJobId: task.repairJobId,
    userId,
    eventType: "task_status_changed",
    fieldChanged: "task_status",
    oldValue: task.status,
    newValue: status,
    comment: status === "problem"
      ? `Task "${task.title}" — Problem: ${problemCategory}${problemNote ? `. ${problemNote}` : ""}`
      : `Task "${task.title}" → ${status}`,
  });

  // Auto-update repair status based on task progress
  await autoUpdateRepairStatus(task.repairJobId);

  return { success: true };
}

// ─────────────────────────────────────────────────────────────────────────────
// AUTO STATUS: sync repair status based on task progress
// ─────────────────────────────────────────────────────────────────────────────

async function autoUpdateRepairStatus(repairJobId: string) {
  const tasks = await db
    .select({ status: repairTasks.status })
    .from(repairTasks)
    .where(eq(repairTasks.repairJobId, repairJobId));

  if (tasks.length === 0) return;

  const allDone = tasks.every((t) => t.status === "done");
  const anyInProgress = tasks.some((t) => t.status === "in_progress");
  const anyProblem = tasks.some((t) => t.status === "problem");

  const [job] = await db
    .select({ status: repairJobs.status })
    .from(repairJobs)
    .where(eq(repairJobs.id, repairJobId));

  if (!job) return;

  // Only auto-update if status is in a garage-relevant state
  const garageStatuses = ["scheduled", "in_progress", "blocked"];
  if (!garageStatuses.includes(job.status) && job.status !== "completed") return;

  if (allDone && job.status !== "completed") {
    await db
      .update(repairJobs)
      .set({
        status: "completed",
        completedAt: new Date(),
        finalCheckStatus: "pending",
        updatedAt: new Date(),
      })
      .where(eq(repairJobs.id, repairJobId));
  } else if (anyProblem && job.status !== "blocked") {
    await db
      .update(repairJobs)
      .set({ status: "blocked", updatedAt: new Date() })
      .where(eq(repairJobs.id, repairJobId));
  } else if (anyInProgress && job.status === "scheduled") {
    await db
      .update(repairJobs)
      .set({ status: "in_progress", updatedAt: new Date() })
      .where(eq(repairJobs.id, repairJobId));
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// GARAGE COMMENT (uses communication log)
// ─────────────────────────────────────────────────────────────────────────────

export async function addGarageComment(repairJobId: string, summary: string) {
  const session = await requireAuth();

  await db.insert(communicationLogs).values({
    repairJobId,
    userId: session.user.id,
    contactMethod: "in_person",
    direction: "inbound",
    contactPerson: session.user.name ?? "Garage",
    summary,
  });

  await db
    .update(repairJobs)
    .set({ lastContactAt: new Date(), updatedAt: new Date() })
    .where(eq(repairJobs.id, repairJobId));

  // Notify office
  const [jobInfo] = await db
    .select({ publicCode: repairJobs.publicCode })
    .from(repairJobs)
    .where(eq(repairJobs.id, repairJobId));
  await notifyOffice(
    repairJobId,
    `💬 Garage opmerking — ${jobInfo?.publicCode ?? ""}`,
    summary,
    "garage_comment"
  );

  return { success: true };
}

// ─────────────────────────────────────────────────────────────────────────────
// SUGGEST EXTRA TASK (from garage, not yet approved)
// ─────────────────────────────────────────────────────────────────────────────

export async function suggestExtraTask(
  repairJobId: string,
  title: string,
  description?: string,
  priority?: string
) {
  const session = await requireAuth();

  // Get max sort order
  const [maxSort] = await db
    .select({ max: sql<number>`coalesce(max(${repairTasks.sortOrder}), 0)` })
    .from(repairTasks)
    .where(eq(repairTasks.repairJobId, repairJobId));

  const [task] = await db
    .insert(repairTasks)
    .values({
      repairJobId,
      title,
      description: description ?? null,
      source: "garage",
      sortOrder: (maxSort?.max ?? 0) + 1,
    })
    .returning();

  // Log event
  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: session.user.id,
    eventType: "task_suggested",
    comment: `Garage suggested: "${title}"${description ? ` — ${description}` : ""}`,
  });

  // Notify office
  const [jobInfo] = await db
    .select({ publicCode: repairJobs.publicCode })
    .from(repairJobs)
    .where(eq(repairJobs.id, repairJobId));
  await notifyOffice(
    repairJobId,
    `➕ Garage taak voorstel — ${jobInfo?.publicCode ?? ""}`,
    `"${title}"${description ? `: ${description}` : ""}`,
    "garage_task_suggestion"
  );

  return task;
}

// ─────────────────────────────────────────────────────────────────────────────
// REQUEST PART (from garage — creates a part request + notifies office)
// ─────────────────────────────────────────────────────────────────────────────

export async function garageRequestPart(repairJobId: string, partName: string) {
  const session = await requireAuth();

  const [request] = await db
    .insert(partRequests)
    .values({
      repairJobId,
      partName,
      quantity: 1,
      status: "requested",
      notes: `Requested by garage (${session.user.name ?? "technician"})`,
    })
    .returning();

  // Log event
  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: session.user.id,
    eventType: "part_requested",
    comment: `Garage requested part: "${partName}"`,
  });

  // Notify office
  const [jobInfo] = await db
    .select({ publicCode: repairJobs.publicCode })
    .from(repairJobs)
    .where(eq(repairJobs.id, repairJobId));
  await notifyOffice(
    repairJobId,
    `📦 Onderdeel aangevraagd — ${jobInfo?.publicCode ?? ""}`,
    `"${partName}"`,
    "garage_part_request"
  );

  revalidatePath(`/garage/repairs/${repairJobId}`);
  revalidatePath(`/repairs/${repairJobId}`);
  revalidatePath("/parts");

  return request;
}

// ─────────────────────────────────────────────────────────────────────────────
// FINAL CHECK
// ─────────────────────────────────────────────────────────────────────────────

export async function completeFinalCheck(repairJobId: string, notes?: string) {
  const session = await requireAuth();

  await db
    .update(repairJobs)
    .set({
      finalCheckStatus: "passed",
      finalCheckByUserId: session.user.id,
      finalCheckAt: new Date(),
      finalCheckNotes: notes ?? null,
      updatedAt: new Date(),
    })
    .where(eq(repairJobs.id, repairJobId));

  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: session.user.id,
    eventType: "final_check_passed",
    comment: notes ? `Final check passed. ${notes}` : "Final check passed.",
  });

  return { success: true };
}

export async function failFinalCheck(repairJobId: string, notes: string) {
  const session = await requireAuth();

  await db
    .update(repairJobs)
    .set({
      finalCheckStatus: "failed",
      finalCheckByUserId: session.user.id,
      finalCheckAt: new Date(),
      finalCheckNotes: notes,
      status: "in_progress",
      completedAt: null,
      updatedAt: new Date(),
    })
    .where(eq(repairJobs.id, repairJobId));

  // Reset all "done" tasks back to "review" so garage re-checks
  await db
    .update(repairTasks)
    .set({ status: "review", updatedAt: new Date() })
    .where(
      and(
        eq(repairTasks.repairJobId, repairJobId),
        eq(repairTasks.status, "done")
      )
    );

  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: session.user.id,
    eventType: "final_check_failed",
    comment: `Final check failed: ${notes}`,
  });

  return { success: true };
}

// ─────────────────────────────────────────────────────────────────────────────
// TASK MANAGEMENT (from office)
// ─────────────────────────────────────────────────────────────────────────────

export async function addRepairTask(
  repairJobId: string,
  data: {
    title: string;
    titleEs?: string;
    titleNl?: string;
    description?: string;
    estimatedHours?: number;
    hourlyRate?: number;
    billable?: boolean;
    includeInEstimate?: boolean;
  }
) {
  const session = await requireAuth();

  const [maxSort] = await db
    .select({ max: sql<number>`coalesce(max(${repairTasks.sortOrder}), 0)` })
    .from(repairTasks)
    .where(eq(repairTasks.repairJobId, repairJobId));

  const [task] = await db
    .insert(repairTasks)
    .values({
      repairJobId,
      title: data.title,
      titleEs: data.titleEs ?? null,
      titleNl: data.titleNl ?? null,
      description: data.description ?? null,
      estimatedHours: data.estimatedHours != null ? String(data.estimatedHours) : null,
      hourlyRate: data.hourlyRate != null ? String(data.hourlyRate) : null,
      billable: data.billable ?? true,
      includeInEstimate: data.includeInEstimate ?? true,
      source: "office",
      sortOrder: (maxSort?.max ?? 0) + 1,
      approvedAt: new Date(),
    })
    .returning();

  return task;
}

export async function deleteRepairTask(taskId: string) {
  const session = await requireAuth();

  const [task] = await db
    .select({ repairJobId: repairTasks.repairJobId, title: repairTasks.title })
    .from(repairTasks)
    .where(eq(repairTasks.id, taskId));

  if (!task) throw new Error("Task not found");

  await db.delete(repairTasks).where(eq(repairTasks.id, taskId));

  await db.insert(repairJobEvents).values({
    repairJobId: task.repairJobId,
    userId: session.user.id,
    eventType: "task_deleted",
    comment: `Task removed: "${task.title}"`,
  });

  return { success: true };
}

export async function approveGarageTask(taskId: string) {
  const session = await requireAuth();

  await db
    .update(repairTasks)
    .set({
      approvedAt: new Date(),
      approvedByUserId: session.user.id,
      updatedAt: new Date(),
    })
    .where(eq(repairTasks.id, taskId));

  return { success: true };
}

export async function getRepairTasks(repairJobId: string) {
  return db
    .select()
    .from(repairTasks)
    .where(eq(repairTasks.repairJobId, repairJobId))
    .orderBy(asc(repairTasks.sortOrder), asc(repairTasks.createdAt));
}

export async function updateRepairTaskPricing(
  taskId: string,
  data: {
    estimatedHours?: number | null;
    actualHours?: number | null;
    hourlyRate?: number | null;
    billable?: boolean;
    includeInEstimate?: boolean;
  }
) {
  await requireAuth();
  const updates: Record<string, unknown> = { updatedAt: new Date() };
  if (data.estimatedHours !== undefined) updates.estimatedHours = data.estimatedHours != null ? String(data.estimatedHours) : null;
  if (data.actualHours !== undefined) updates.actualHours = data.actualHours != null ? String(data.actualHours) : null;
  if (data.hourlyRate !== undefined) updates.hourlyRate = data.hourlyRate != null ? String(data.hourlyRate) : null;
  if (data.billable !== undefined) updates.billable = data.billable;
  if (data.includeInEstimate !== undefined) updates.includeInEstimate = data.includeInEstimate;
  await db.update(repairTasks).set(updates).where(eq(repairTasks.id, taskId));
  revalidatePath("/");
}

// ─────────────────────────────────────────────────────────────────────────────
// REPAIR WORKERS (who worked on a repair)
// ─────────────────────────────────────────────────────────────────────────────

export async function getRepairWorkers(repairJobId: string) {
  return db
    .select({
      id: repairWorkers.id,
      userId: repairWorkers.userId,
      userName: users.name,
      note: repairWorkers.note,
      createdAt: repairWorkers.createdAt,
    })
    .from(repairWorkers)
    .innerJoin(users, eq(repairWorkers.userId, users.id))
    .where(eq(repairWorkers.repairJobId, repairJobId))
    .orderBy(asc(repairWorkers.createdAt));
}

/** Toggle "I worked on this" — adds or removes the current user */
export async function toggleMyWorker(repairJobId: string) {
  const session = await requireAuth();
  const userId = session.user.id;

  const existing = await db
    .select({ id: repairWorkers.id })
    .from(repairWorkers)
    .where(and(eq(repairWorkers.repairJobId, repairJobId), eq(repairWorkers.userId, userId)));

  if (existing.length > 0) {
    await db.delete(repairWorkers).where(eq(repairWorkers.id, existing[0].id));
  } else {
    await db.insert(repairWorkers).values({
      repairJobId,
      userId,
      addedByUserId: userId,
    });
  }

  revalidatePath(`/garage/repairs/${repairJobId}`);
  revalidatePath(`/repairs/${repairJobId}`);
}

/** Admin/staff: add a worker to a repair */
export async function addRepairWorker(repairJobId: string, userId: string) {
  const session = await requireAuth();

  // Check not already added
  const existing = await db
    .select({ id: repairWorkers.id })
    .from(repairWorkers)
    .where(and(eq(repairWorkers.repairJobId, repairJobId), eq(repairWorkers.userId, userId)));

  if (existing.length > 0) return;

  await db.insert(repairWorkers).values({
    repairJobId,
    userId,
    addedByUserId: session.user.id,
  });

  revalidatePath(`/repairs/${repairJobId}`);
}

/** Admin/staff: remove a worker from a repair */
export async function removeRepairWorker(repairJobId: string, userId: string) {
  await requireAuth();
  await db.delete(repairWorkers).where(
    and(eq(repairWorkers.repairJobId, repairJobId), eq(repairWorkers.userId, userId))
  );
  revalidatePath(`/repairs/${repairJobId}`);
}

/** Update a worker's note */
export async function updateWorkerNote(workerId: string, note: string) {
  await requireAuth();
  await db.update(repairWorkers).set({ note: note || null }).where(eq(repairWorkers.id, workerId));
}

/** Get all active users (for worker assignment dropdown) */
export async function getActiveUsers() {
  return db
    .select({ id: users.id, name: users.name, role: users.role })
    .from(users)
    .where(eq(users.active, true))
    .orderBy(users.name);
}

// ─────────────────────────────────────────────────────────────────────────────
// FINDINGS: technicians log inspection findings
// ─────────────────────────────────────────────────────────────────────────────

export async function addFinding(
  repairJobId: string,
  data: {
    category: string;
    description: string;
    severity: string;
    requiresFollowUp?: boolean;
    requiresCustomerApproval?: boolean;
  }
) {
  const session = await requireAuth();

  const [finding] = await db
    .insert(repairFindings)
    .values({
      repairJobId,
      category: data.category as any,
      description: data.description,
      severity: data.severity as any,
      requiresFollowUp: data.requiresFollowUp ?? false,
      requiresCustomerApproval: data.requiresCustomerApproval ?? false,
      createdByUserId: session.user.id,
    })
    .returning();

  // Log timeline event
  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: session.user.id,
    eventType: "finding_added",
    comment: `${data.severity} finding (${data.category}): ${data.description}`,
  });

  // Auto-behaviors based on severity/flags
  if (data.severity === "critical") {
    // Auto-escalate priority to high if currently normal or low
    const [job] = await db
      .select({ priority: repairJobs.priority })
      .from(repairJobs)
      .where(eq(repairJobs.id, repairJobId));
    if (job && (job.priority === "normal" || job.priority === "low")) {
      await db
        .update(repairJobs)
        .set({ priority: "high", updatedAt: new Date() })
        .where(eq(repairJobs.id, repairJobId));
    }
    await notifyOffice(
      repairJobId,
      `⚠️ Critical finding: ${data.description}`,
      `Category: ${data.category}, Severity: CRITICAL`,
      "garage_critical_finding"
    );
  }

  if (data.requiresCustomerApproval) {
    await db
      .update(repairJobs)
      .set({
        customerResponseStatus: "waiting_response",
        updatedAt: new Date(),
      })
      .where(eq(repairJobs.id, repairJobId));
    await notifyOffice(
      repairJobId,
      `Customer approval required: ${data.description}`,
      `Category: ${data.category}`,
      "garage_approval_needed"
    );
  } else if (data.severity !== "critical") {
    await notifyOffice(
      repairJobId,
      `Finding logged: ${data.description}`,
      `Category: ${data.category}, Severity: ${data.severity}`,
      "garage_finding"
    );
  }

  // Set relevant flags based on category
  const flagMap: Record<string, Record<string, boolean>> = {
    water_damage: { waterDamageRiskFlag: true },
    tyres: { tyresFlag: true },
    lighting: { lightsFlag: true },
    brakes: { brakesFlag: true },
    windows: { windowsFlag: true },
    seals: { sealsFlag: true },
  };
  const flagUpdate = flagMap[data.category];
  if (flagUpdate) {
    await db
      .update(repairJobs)
      .set({ ...flagUpdate, updatedAt: new Date() })
      .where(eq(repairJobs.id, repairJobId));
  }

  if (data.requiresFollowUp) {
    await db
      .update(repairJobs)
      .set({ followUpRequiredFlag: true, updatedAt: new Date() })
      .where(eq(repairJobs.id, repairJobId));
  }

  revalidatePath(`/garage/repairs/${repairJobId}`);
  revalidatePath(`/repairs/${repairJobId}`);
  return finding;
}

export async function getRepairFindings(repairJobId: string) {
  return db
    .select({
      id: repairFindings.id,
      category: repairFindings.category,
      description: repairFindings.description,
      severity: repairFindings.severity,
      requiresFollowUp: repairFindings.requiresFollowUp,
      requiresCustomerApproval: repairFindings.requiresCustomerApproval,
      resolvedAt: repairFindings.resolvedAt,
      createdAt: repairFindings.createdAt,
      createdByName: users.name,
    })
    .from(repairFindings)
    .leftJoin(users, eq(repairFindings.createdByUserId, users.id))
    .where(eq(repairFindings.repairJobId, repairJobId))
    .orderBy(desc(repairFindings.createdAt));
}

export async function resolveFinding(findingId: string) {
  await requireAuth();
  await db
    .update(repairFindings)
    .set({ resolvedAt: new Date() })
    .where(eq(repairFindings.id, findingId));
  revalidatePath("/");
}

export async function deleteFinding(findingId: string) {
  await requireRole("admin");
  await db.delete(repairFindings).where(eq(repairFindings.id, findingId));
  revalidatePath("/");
}

// ─────────────────────────────────────────────────────────────────────────────
// BLOCKERS: job-level blockers
// ─────────────────────────────────────────────────────────────────────────────

export async function addBlocker(
  repairJobId: string,
  data: { reason: string; description?: string }
) {
  const session = await requireAuth();

  const [blocker] = await db
    .insert(repairBlockers)
    .values({
      repairJobId,
      reason: data.reason as any,
      description: data.description ?? null,
      createdByUserId: session.user.id,
    })
    .returning();

  // Log timeline event
  await db.insert(repairJobEvents).values({
    repairJobId,
    userId: session.user.id,
    eventType: "blocker_added",
    comment: `Blocker: ${data.reason}${data.description ? ` — ${data.description}` : ""}`,
  });

  // Auto-update repair status based on blocker reason
  const statusMap: Record<string, string> = {
    waiting_parts: "waiting_parts",
    waiting_customer: "waiting_customer",
  };
  const newStatus = statusMap[data.reason] ?? "blocked";
  await db
    .update(repairJobs)
    .set({
      status: newStatus as any,
      currentBlocker: data.description || data.reason,
      updatedAt: new Date(),
    })
    .where(eq(repairJobs.id, repairJobId));

  // Update customer response status for waiting_customer
  if (data.reason === "waiting_customer") {
    await db
      .update(repairJobs)
      .set({ customerResponseStatus: "waiting_response" })
      .where(eq(repairJobs.id, repairJobId));
  }

  // Parts required flag for waiting_parts
  if (data.reason === "waiting_parts") {
    await db
      .update(repairJobs)
      .set({ partsRequiredFlag: true })
      .where(eq(repairJobs.id, repairJobId));
  }

  await notifyOffice(
    repairJobId,
    `🚫 Blocker: ${data.reason}`,
    data.description ?? undefined,
    "garage_blocker"
  );

  revalidatePath(`/garage/repairs/${repairJobId}`);
  revalidatePath(`/repairs/${repairJobId}`);
  return blocker;
}

export async function resolveBlocker(blockerId: string) {
  const session = await requireAuth();

  const [blocker] = await db
    .select({
      repairJobId: repairBlockers.repairJobId,
      reason: repairBlockers.reason,
    })
    .from(repairBlockers)
    .where(eq(repairBlockers.id, blockerId));

  if (!blocker) throw new Error("Blocker not found");

  await db
    .update(repairBlockers)
    .set({
      active: false,
      resolvedAt: new Date(),
      resolvedByUserId: session.user.id,
    })
    .where(eq(repairBlockers.id, blockerId));

  // Log event
  await db.insert(repairJobEvents).values({
    repairJobId: blocker.repairJobId,
    userId: session.user.id,
    eventType: "blocker_resolved",
    comment: `Blocker resolved: ${blocker.reason}`,
  });

  // Check if there are other active blockers
  const [remaining] = await db
    .select({ cnt: count() })
    .from(repairBlockers)
    .where(
      and(
        eq(repairBlockers.repairJobId, blocker.repairJobId),
        eq(repairBlockers.active, true)
      )
    );

  // If no more active blockers, move back to in_progress
  if (!remaining || remaining.cnt === 0) {
    await db
      .update(repairJobs)
      .set({
        status: "in_progress",
        currentBlocker: null,
        updatedAt: new Date(),
      })
      .where(eq(repairJobs.id, blocker.repairJobId));
  }

  revalidatePath(`/garage/repairs/${blocker.repairJobId}`);
  revalidatePath(`/repairs/${blocker.repairJobId}`);
}

export async function getRepairBlockers(repairJobId: string) {
  return db
    .select({
      id: repairBlockers.id,
      reason: repairBlockers.reason,
      description: repairBlockers.description,
      active: repairBlockers.active,
      createdAt: repairBlockers.createdAt,
      resolvedAt: repairBlockers.resolvedAt,
      createdByName: users.name,
    })
    .from(repairBlockers)
    .leftJoin(users, eq(repairBlockers.createdByUserId, users.id))
    .where(eq(repairBlockers.repairJobId, repairJobId))
    .orderBy(desc(repairBlockers.active), desc(repairBlockers.createdAt));
}

// ─────────────────────────────────────────────────────────────────────────────
// QUICK STATS (for empty state / dashboard strip)
// ─────────────────────────────────────────────────────────────────────────────

export async function getGarageQuickStats() {
  await requireAuth();

  const now = new Date();

  // Tomorrow range
  const tomorrowStart = new Date(now);
  tomorrowStart.setDate(tomorrowStart.getDate() + 1);
  tomorrowStart.setHours(0, 0, 0, 0);
  const tomorrowEnd = new Date(tomorrowStart);
  tomorrowEnd.setHours(23, 59, 59, 999);

  const [tomorrowJobs] = await db
    .select({ count: count() })
    .from(repairJobs)
    .where(
      and(
        isNull(repairJobs.deletedAt),
        isNull(repairJobs.archivedAt),
        gte(repairJobs.dueDate, tomorrowStart),
        lte(repairJobs.dueDate, tomorrowEnd)
      )
    );

  // Waiting parts (any active job with pending parts)
  const [waitingParts] = await db
    .select({ count: count() })
    .from(repairJobs)
    .where(
      and(
        isNull(repairJobs.deletedAt),
        isNull(repairJobs.archivedAt),
        eq(repairJobs.status, "waiting_parts")
      )
    );

  // Urgent/high priority active jobs
  const [urgentJobs] = await db
    .select({ count: count() })
    .from(repairJobs)
    .where(
      and(
        isNull(repairJobs.deletedAt),
        isNull(repairJobs.archivedAt),
        inArray(repairJobs.priority, ["urgent", "high"]),
        inArray(repairJobs.status, [
          "new", "todo", "scheduled", "in_progress", "waiting_parts", "waiting_customer",
        ])
      )
    );

  // Unassigned active jobs
  const [unassigned] = await db
    .select({ count: count() })
    .from(repairJobs)
    .where(
      and(
        isNull(repairJobs.deletedAt),
        isNull(repairJobs.archivedAt),
        isNull(repairJobs.assignedUserId),
        inArray(repairJobs.status, [
          "new", "todo", "scheduled", "in_progress",
        ])
      )
    );

  return {
    tomorrowCount: Number(tomorrowJobs.count),
    waitingPartsCount: Number(waitingParts.count),
    urgentCount: Number(urgentJobs.count),
    unassignedCount: Number(unassigned.count),
  };
}
