"use server";

import { db } from "@/lib/db";
import { actionReminders, repairJobs, customers } from "@/lib/db/schema";
import { requireAuth } from "@/lib/auth-utils";
import { eq, and, isNull, desc, lte, count } from "drizzle-orm";
import { revalidatePath } from "next/cache";

export async function getActiveReminders() {
  const session = await requireAuth();

  const reminders = await db
    .select({
      id: actionReminders.id,
      reminderType: actionReminders.reminderType,
      title: actionReminders.title,
      description: actionReminders.description,
      dueAt: actionReminders.dueAt,
      autoGenerated: actionReminders.autoGenerated,
      triggerEvent: actionReminders.triggerEvent,
      repairJobId: actionReminders.repairJobId,
      publicCode: repairJobs.publicCode,
      customerName: customers.name,
      createdAt: actionReminders.createdAt,
    })
    .from(actionReminders)
    .leftJoin(repairJobs, eq(actionReminders.repairJobId, repairJobs.id))
    .leftJoin(customers, eq(repairJobs.customerId, customers.id))
    .where(
      and(
        isNull(actionReminders.completedAt),
        isNull(actionReminders.dismissedAt)
      )
    )
    .orderBy(desc(actionReminders.createdAt))
    .limit(50);

  return reminders;
}

export async function getActiveReminderCount() {
  const session = await requireAuth();

  const [result] = await db
    .select({ count: count() })
    .from(actionReminders)
    .where(
      and(
        isNull(actionReminders.completedAt),
        isNull(actionReminders.dismissedAt)
      )
    );

  return result?.count ?? 0;
}

export async function completeReminder(reminderId: string) {
  const session = await requireAuth();

  await db
    .update(actionReminders)
    .set({ completedAt: new Date() })
    .where(eq(actionReminders.id, reminderId));

  revalidatePath("/");
}

export async function dismissReminder(reminderId: string) {
  const session = await requireAuth();

  await db
    .update(actionReminders)
    .set({ dismissedAt: new Date() })
    .where(eq(actionReminders.id, reminderId));

  revalidatePath("/");
}

export async function createReminder(data: {
  repairJobId?: string;
  reminderType: string;
  title: string;
  description?: string;
  dueAt?: Date;
}) {
  const session = await requireAuth();

  await db.insert(actionReminders).values({
    repairJobId: data.repairJobId,
    userId: session.user.id,
    reminderType: data.reminderType as any,
    title: data.title,
    description: data.description,
    dueAt: data.dueAt,
    autoGenerated: false,
  });

  revalidatePath("/");
}

// Auto-generate reminders based on status changes
export async function autoGenerateReminder(
  repairJobId: string,
  newStatus: string,
  customerResponse?: string
) {
  const REMINDER_RULES: {
    condition: (status: string, response?: string) => boolean;
    type: string;
    title: string;
    description: string;
  }[] = [
    {
      condition: (_, response) => response === "approved",
      type: "create_invoice",
      title: "Create invoice in Holded",
      description:
        "Customer has approved the repair. Create an invoice in Holded for this job.",
    },
    {
      condition: (status) => status === "completed",
      type: "create_invoice",
      title: "Create final invoice in Holded",
      description:
        "Repair is completed. Create and send the final invoice via Holded.",
    },
    {
      condition: (status) => status === "waiting_parts",
      type: "check_delivery",
      title: "Check parts delivery status",
      description:
        "Parts have been ordered. Check delivery status in a few days.",
    },
    {
      condition: (status) => status === "quote_needed",
      type: "send_quote",
      title: "Send quote to customer",
      description: "A quote needs to be prepared and sent to the customer.",
    },
    {
      condition: (status) => status === "waiting_customer",
      type: "follow_up_customer",
      title: "Follow up with customer",
      description:
        "Customer has been contacted. Follow up if no response within 3 days.",
    },
  ];

  for (const rule of REMINDER_RULES) {
    if (rule.condition(newStatus, customerResponse)) {
      // Check if a similar active reminder already exists
      const existing = await db
        .select({ id: actionReminders.id })
        .from(actionReminders)
        .where(
          and(
            eq(actionReminders.repairJobId, repairJobId),
            eq(actionReminders.reminderType, rule.type as any),
            isNull(actionReminders.completedAt),
            isNull(actionReminders.dismissedAt)
          )
        )
        .limit(1);

      if (existing.length === 0) {
        const dueAt = new Date();
        if (rule.type === "follow_up_customer" || rule.type === "check_delivery") {
          dueAt.setDate(dueAt.getDate() + 3);
        } else {
          dueAt.setDate(dueAt.getDate() + 1);
        }

        await db.insert(actionReminders).values({
          repairJobId,
          reminderType: rule.type as any,
          title: rule.title,
          description: rule.description,
          dueAt,
          autoGenerated: true,
          triggerEvent: `status_change:${newStatus}${customerResponse ? `,response:${customerResponse}` : ""}`,
        });
      }
    }
  }
}
