"use server";

import { db } from "@/lib/db";
import { actionReminders, repairJobs, customers, repairMessages } from "@/lib/db/schema";
import { requireAuth } from "@/lib/auth-utils";
import { eq, and, isNull, desc, sql } from "drizzle-orm";
import { revalidatePath } from "next/cache";

/**
 * Auto-dismiss reminders that have become irrelevant.
 *
 * The cron auto-creates lots of reminders (e.g. "create invoice in Holded"
 * whenever a status flips), but they don't get removed when the underlying
 * issue is resolved elsewhere. That's why users see "99+" in the bell.
 *
 * Rules for stale reminders (auto-dismissed when this runs):
 *   - create_invoice / send_quote on a repair that already has the doc.
 *   - Any reminder for a repair that is archived, rejected, no_damage, or invoiced.
 *   - Any reminder for a soft-deleted repair (cascade should handle, but belt-and-braces).
 *   - Older than 30 days (auto-stale; user has clearly ignored).
 *   - Garage feedback events older than 7 days (already in repair history).
 */
async function pruneStaleReminders(): Promise<void> {
  const stalePaths: string[] = [];

  // 1. create_invoice on repairs that already have an invoice → dismiss.
  stalePaths.push(`(reminder_type = 'create_invoice' AND EXISTS (
    SELECT 1 FROM repair_jobs rj
    WHERE rj.id = action_reminders.repair_job_id
      AND rj.holded_invoice_id IS NOT NULL
  ))`);

  // 2. send_quote on repairs that already have a quote → dismiss.
  stalePaths.push(`(reminder_type = 'send_quote' AND EXISTS (
    SELECT 1 FROM repair_jobs rj
    WHERE rj.id = action_reminders.repair_job_id
      AND rj.holded_quote_id IS NOT NULL
  ))`);

  // 3. Any reminder on a finalized / archived / rejected / invoiced / no_damage repair.
  stalePaths.push(`(EXISTS (
    SELECT 1 FROM repair_jobs rj
    WHERE rj.id = action_reminders.repair_job_id
      AND (rj.status IN ('archived', 'rejected', 'no_damage', 'invoiced')
           OR rj.deleted_at IS NOT NULL
           OR rj.archived_at IS NOT NULL)
  ))`);

  // 4. Older than 30 days (any).
  stalePaths.push(`(action_reminders.created_at < NOW() - INTERVAL '30 days')`);

  const whereClause = `(action_reminders.completed_at IS NULL AND action_reminders.dismissed_at IS NULL) AND (${stalePaths.join(" OR ")})`;

  await db.execute(sql.raw(
    `UPDATE action_reminders SET dismissed_at = NOW() WHERE ${whereClause}`,
  ));
}

export async function getActiveReminders() {
  await requireAuth();
  await pruneStaleReminders();

  const reminders = await db
    .select({
      id: actionReminders.id,
      reminderType: actionReminders.reminderType,
      title: actionReminders.title,
      description: actionReminders.description,
      dueAt: actionReminders.dueAt,
      autoGenerated: actionReminders.autoGenerated,
      triggerEvent: actionReminders.triggerEvent,
      repairJobId: actionReminders.repairJobId,
      publicCode: repairJobs.publicCode,
      customerName: customers.name,
      createdAt: actionReminders.createdAt,
    })
    .from(actionReminders)
    .leftJoin(repairJobs, eq(actionReminders.repairJobId, repairJobs.id))
    .leftJoin(customers, eq(repairJobs.customerId, customers.id))
    .where(
      and(
        isNull(actionReminders.completedAt),
        isNull(actionReminders.dismissedAt)
      )
    )
    .orderBy(desc(actionReminders.createdAt))
    .limit(50);

  return reminders;
}

/** Compact summary for the badge: separate overdue from total, no DB join.
 *  Unread garage replies are counted as overdue (they always need a glance). */
export async function getInboxBadgeSummary() {
  await requireAuth();

  const [rows, garageRow] = await Promise.all([
    db
      .select({
        id: actionReminders.id,
        dueAt: actionReminders.dueAt,
      })
      .from(actionReminders)
      .where(
        and(
          isNull(actionReminders.completedAt),
          isNull(actionReminders.dismissedAt),
        ),
      )
      .limit(500),
    db
      .select({ count: sql<number>`count(*)::int` })
      .from(repairMessages)
      .where(
        and(
          eq(repairMessages.direction, "garage_to_admin"),
          isNull(repairMessages.readAt),
        ),
      ),
  ]);

  const now = Date.now();
  let overdue = 0;
  for (const r of rows) {
    if (r.dueAt && new Date(r.dueAt).getTime() < now) overdue++;
  }
  const garageUnread = Number(garageRow[0]?.count ?? 0);
  return {
    total: rows.length + garageUnread,
    overdue: overdue + garageUnread,
    garageUnread,
  };
}

export async function completeReminder(reminderId: string) {
  const session = await requireAuth();

  await db
    .update(actionReminders)
    .set({ completedAt: new Date() })
    .where(eq(actionReminders.id, reminderId));

  revalidatePath("/");
}

export async function dismissReminder(reminderId: string) {
  const session = await requireAuth();

  await db
    .update(actionReminders)
    .set({ dismissedAt: new Date() })
    .where(eq(actionReminders.id, reminderId));

  revalidatePath("/");
}

export async function createReminder(data: {
  repairJobId?: string;
  reminderType: string;
  title: string;
  description?: string;
  dueAt?: Date;
}) {
  const session = await requireAuth();

  await db.insert(actionReminders).values({
    repairJobId: data.repairJobId,
    userId: session.user.id,
    reminderType: data.reminderType as any,
    title: data.title,
    description: data.description,
    dueAt: data.dueAt,
    autoGenerated: false,
  });

  revalidatePath("/");
}

// Auto-generate reminders based on status changes
export async function autoGenerateReminder(
  repairJobId: string,
  newStatus: string,
  customerResponse?: string
) {
  const REMINDER_RULES: {
    condition: (status: string, response?: string) => boolean;
    type: string;
    title: string;
    description: string;
  }[] = [
    {
      condition: (_, response) => response === "approved",
      type: "create_invoice",
      title: "Create invoice in Holded",
      description:
        "Customer has approved the repair. Create an invoice in Holded for this job.",
    },
    {
      condition: (status) => status === "completed",
      type: "create_invoice",
      title: "Create final invoice in Holded",
      description:
        "Repair is completed. Create and send the final invoice via Holded.",
    },
    {
      condition: (status) => status === "ready_for_check",
      type: "review_completion",
      title: "Review garage completion",
      description:
        "Garage has marked this repair as done. Review the work and approve or send back.",
    },
    {
      condition: (status) => status === "waiting_parts",
      type: "check_delivery",
      title: "Check parts delivery status",
      description:
        "Parts have been ordered. Check delivery status in a few days.",
    },
    {
      condition: (status) => status === "quote_needed",
      type: "send_quote",
      title: "Send quote to customer",
      description: "A quote needs to be prepared and sent to the customer.",
    },
    {
      condition: (status, response) =>
        status === "waiting_customer" && response !== "reply_not_required",
      type: "follow_up_customer",
      title: "Follow up with customer",
      description:
        "Customer has been contacted. Follow up if no response within 3 days.",
    },
  ];

  for (const rule of REMINDER_RULES) {
    if (rule.condition(newStatus, customerResponse)) {
      // Check if a similar active reminder already exists
      const existing = await db
        .select({ id: actionReminders.id })
        .from(actionReminders)
        .where(
          and(
            eq(actionReminders.repairJobId, repairJobId),
            eq(actionReminders.reminderType, rule.type as any),
            isNull(actionReminders.completedAt),
            isNull(actionReminders.dismissedAt)
          )
        )
        .limit(1);

      if (existing.length === 0) {
        const dueAt = new Date();
        if (rule.type === "follow_up_customer" || rule.type === "check_delivery") {
          dueAt.setDate(dueAt.getDate() + 3);
        } else {
          dueAt.setDate(dueAt.getDate() + 1);
        }

        await db.insert(actionReminders).values({
          repairJobId,
          reminderType: rule.type as any,
          title: rule.title,
          description: rule.description,
          dueAt,
          autoGenerated: true,
          triggerEvent: `status_change:${newStatus}${customerResponse ? `,response:${customerResponse}` : ""}`,
        });
      }
    }
  }
}
